import { Aside, H2, H3, Lede, Note, SeeAlso, TableFrame } from '../../components/Doc.jsx';
import { Link } from '../../lib/router.jsx';

const PRIMITIVES = [
  ['Style', 'a class per role on a run'],
  [
    'Conceal',
    'font-size: 0.01px — the same hairline trick as Apple, so the character count stays 1:1 with the source',
  ],
  [
    'InlineWidget / BlockWidget',
    'a host view marked data-mde-ignore, alongside the concealed source',
  ],
  ['Gutter', 'the marker character, themed'],
  ['Hit', 'hit-tested against the live decorations on click'],
];

export default function Web() {
  return (
    <>
      <H2 id="not-a-framework">A thin layer over contenteditable</H2>
      <Lede>
        The browser supplies IME, spellcheck, accessibility and touch selection; we supply span
        application and replaced elements — analogous to the native TextKit projection. This sits <em>at</em> the level
        of the browser’s text engine, not above it.
      </Lede>
      <p>
        CodeMirror 6 was rejected for that reason. It is a framework above the browser’s text engine
        with its own decoration and transaction model, so building against it and TextKit would
        translate one protocol into two foreign vocabularies and let{' '}
        <Link to="/docs/concepts/widgets">the widget semantics</Link> drift apart — which is the
        different widget and selection behavior between platforms.
      </p>

      <H2 id="invariant">The DOM preserves the Markdown source</H2>
      <Aside tone="note" title="The DOM's text, excluding data-mde-ignore subtrees, is exactly the markdown source">
        Widget views are marked ignored so a chip reading <code>@gabe</code> cannot smuggle its
        label into the document. A single tree walk recovers edits and maps DOM selections to source
        offsets.
      </Aside>

      <H2 id="primitives">How each primitive is drawn</H2>
      <TableFrame className="mt-6">
        <thead>
          <tr>
            <th>Primitive</th>
            <th className="desc">How it is drawn</th>
          </tr>
        </thead>
        <tbody>
          {PRIMITIVES.map(([name, how]) => (
            <tr key={name}>
              <td className="role">{name}</td>
              <td className="desc">{how}</td>
            </tr>
          ))}
        </tbody>
      </TableFrame>
      <Note>
        A GFM table is the deliberate built-in projection: while its caret is elsewhere, the web
        renderer draws a semantic <code>&lt;table&gt;</code> inside a{' '}
        <code>data-mde-ignore</code> view and conceals the pipe source beside it. Clicking the table
        restores those exact source lines for editing; leaving the block brings the table back.
      </Note>

      <H2 id="lessons">Browser implementation details</H2>

      <H3 id="diffing">Recovering edits from DOM changes</H3>
      <p>
        By the time <code>input</code> fires the browser has already mutated the DOM, and it does
        not describe what it did in a form that holds across IME, autocorrect, paste and drag. A
        common-prefix/suffix diff against the mirror recovers the replacement uniformly from all of
        them — and must not cut a surrogate pair in half.
      </p>

      <H3 id="plaintext-only">Using plaintext-only contenteditable</H3>
      <p>
        Plain <code>contenteditable</code> invents <code>&lt;div&gt;</code>s and{' '}
        <code>&lt;br&gt;</code>s on Enter. <code>contenteditable="plaintext-only"</code> inserts a
        real newline character, which is what the document actually contains. Lines are then spans
        in a <code>white-space: pre-wrap</code> container, so a line can be re-rendered without
        touching its neighbours.
      </p>

      <H3 id="line-height">Collapsing line boxes for concealed newlines</H3>
      <p>
        Appending the <code>\n</code> outside the line’s decorated range leaves it unconcealed, so a
        block widget spanning three lines renders as one widget plus two blank lines. Treating the
        newline as an ordinary character of the line lets a block widget conceal it like any other.
      </p>
      <p>
        Concealing the newline is necessary but does not collapse its line box. Concealing shrinks
        <em>glyphs</em>; the line box they sit in is
        sized by the containing block’s strut, which no amount of shrinking the content can get
        under. Three separate things were each contributing a full 27px band: the continuation lines
        themselves, the anonymous line box generated by an inline concealed run sitting after a
        block-level widget view, and the empty inline fragments a block box creates when it splits
        an inline <code>.mde-line</code>.
      </p>
      <Note>
        So the container carries no leading at all (<code>line-height: 0</code>), each{' '}
        <code>.mde-line</code> restores it, a fully concealed line zeroes it again, the line that
        draws a widget becomes a block itself, and the concealed source inside a widget is a
        zero-height block. A test asserts the continuation lines measure exactly zero and that the
        drawn line is no taller than the view it draws.
      </Note>

      <H3 id="conceal-precedence">Conceal-style precedence</H3>
      <p>
        A concealed <code>##</code> is also a heading. <code>.mde-conceal</code> and{' '}
        <code>.mde-h2</code> are both single-class selectors, so without <code>!important</code> the
        heading’s font size silently wins on source order and the markers never collapse. There is a
        test pinned to exactly this.
      </p>

      <H2 id="widget-clicks">Widget wrapper layout</H2>
      <p>
        A plain inline wrapper is one line tall however tall its content is, so a click in the
        middle of an image sails past it — and because the source a widget stands for is concealed
        to a hairline, the browser then maps that click to whatever real text is nearest, which is
        the line below. The click has to be claimed explicitly and the caret placed at the start of
        the source, which is what reveals it.
      </p>

      <H2 id="firefox">Current Firefox limitation</H2>
      <p>
        <code>contenteditable="plaintext-only"</code> is well supported in Chrome and Safari but
        only landed in Firefox recently; older Firefox would need a fallback that intercepts{' '}
        <code>beforeinput</code>. And because the web host re-renders whole lines, a minified paste
        with no newlines in it degrades to O(line) per keystroke — see{' '}
        <Link to="/docs/internals/status">Status and open questions</Link>.
      </p>

      <SeeAlso
        links={[
          {
            to: '/docs/platforms/apple',
            title: 'iOS and macOS',
            note: 'the same primitives against native TextKit',
          },
          { to: '/docs/reference/roles', title: 'Roles and CSS classes', note: 'what to style' },
          { to: '/docs/internals/testing', title: 'Testing', note: 'browser-engine and cross-platform coverage' },
        ]}
      />
    </>
  );
}
